{
    "apiVersion": "radix.equinor.com/v1",
    "kind": "RadixApplication",
    "metadata": { "name": "prespoll" },
    "spec": {
        "environments": [
            { "name": "dev", "build": { "from": "master" } }
        ],
        "components": [
            {
                "name": "main",
                "src": ".",
                "publicPort": "http",
                "ports": [
                    { "name": "http", "port": 5000 }
                ]
            }
        ]
    }
}